version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    env_file:
      - .env
    volumes:
      - .:/app
    command: python tgbot/aiogram_run.py
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:5.0.7-alpine
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
